### ISSUE TITLE
Trakt plugin seems to be removing shows from trakt watchlist?

### ISSUE THREAD

**Issue by night199uk** [trakt/script.trakt#62]
I've not caught this yet to be able to post a log or anything substantive, so apologies if this is noise. I wanted to give a heads-up in case you can find it in code before I can get any debug here. I'll try and get something as soon as I can but this is pretty difficult to trakt down. 

Shows have been disappearing randomly from my trakt watchlist. Certain shows (the ones I watch most) seem to do it very regularly now. At the end of last week I had 30 shows on my watchlist, now I'm down to 24. I'm pretty sure it might be the trakt plugin doing it during sync. I also have flexget synced to my trakt watchlist so the only other option is flexget, but that is read only on the watchlist.

Has anyone else seen this?

**Comment by buckneri** [comment]
ok then what do we use for a list? collection?

**Comment by rectifyer** [comment]
@buckneri you can use a custom list - https://blog.trakt.tv/manage-your-watchlist-personal-lists-9e4fdc521e3d

The collection is intended for items you own or have available to watch locally.

**Comment by buckneri** [comment]
ok. so i want to make a list of shows i often watch so that i can just pull up that list on my media player and watch the latest episode without needing to remember every show that i watch... which list does that? and why would a watch list dump a show once you start watching it if you havent FINISHED watching it??? seems silly. maybe if you add an episode to the list it makes sense because the episode is then watched, but when you add an entire show.. its not watched until.. well you watch it all.

**Comment by buckneri** [comment]
nvm collection does just that.

**Comment by rectifyer** [comment]
The purpose of the watchlist is for items you want to watch, not what you are currently watching. Trakt already knows what you're watching and updates the calendar, progress, etc with that info so there isn't a need to keep items on the watchlist. Unfortunately some apps incorrectly implement the watchlist when they should instead being using either a custom list or the other methods we have available to get a list of all shows you're watching.
